version: "3"
services:
  bj-mariadb:
    image: mariadb:10.9
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=example # REDACTED
      - MARIADB_DATABASE=battle_judge # REDACTED
    networks:
      - backend_bridge
    ports:
      - 3306
    # Bind les script(s) sql pour initialiser la base de données mariadb
    volumes:
      - ./backend/db/scripts/maria-init.sql:/docker-entrypoint-initdb.d/maria-init.sql:ro
  bj-mongodb:
    image: mongo:6.0.3
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=example # REDACTED
      - MONGO_INITDB_ROOT_PASSWORD=example # REDACTED
    networks:
      - backend_bridge
    ports:
      - 27017
    # Bind les script(s) js pour initialiser la base de données mongodb
    volumes:
      - ./backend/db/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  # pwa:
  #   build: .
  #   environment:
  #     - PORT=3000 # REDACTED
  #     - MONGO_URI=mongodb://example:example@bj-mongodb:27017 # REDACTED
  #     - MARIADB_URI=mariadb://root:example@bj-mariadb:3306/battle_judge # REDACTED
  #     - JWT_SECRET=example # REDACTED
  #     - NODE_ENV=production
  #   networks:
  #     - backend_bridge
  #   ports:
  #     - 3000:3000 # REDACTED
  #   depends_on:
  #     - bj-mariadb
  #     - bj-mongodb

  # Nom du service et du host du container 
  # (doit être le même que dans la configuration nginx dans le dossier `dossier_backend/nginx.conf`)
  backend:
    build: ./backend
    environment:
      - PORT=3000 # REDACTED
      - MONGO_URI=mongodb://example:example@bj-mongodb:27017 # REDACTED
      - MARIADB_URI=mariadb://root:example@bj-mariadb:3306/battle_judge # REDACTED
      - JWT_SECRET=example # REDACTED
      - NODE_ENV=production
    networks:
      - backend_bridge
      - frontend_bridge
    ports:
      - 3000 # REDACTED
    depends_on:
      - bj-mariadb
      - bj-mongodb

  frontend:
    # On build le front avec node et on démarre un serveur nginx au port 80 (http)
    build: ./frontend
    environment:
      - NODE_ENV=production
    networks:
      - backend_bridge
      - frontend_bridge
    ports:
      - 80:80
    depends_on:
      - backend

networks:
  backend_bridge:
  frontend_bridge:
